Dev
Moysenko/NFA-converter pull request #1
Opened 2020-10-06 10:40 UTC by Moysenko

2020-10-07 17:32 UTC, akhtyamovpavel requested changes
Добрый день!

Замечаний минимум, но стоит на них посмотреть - в production коде некоторые из них делать совсем не айс.

Буду ждать новой версии!

Если не успею до кр посмотреть, то кодом можно будет пользоваться

2020-10-07 17:32 UTC, akhtyamovpavel commented on automaton_t.py
> +        self.__getitem__(vertex_to)   # in order to add vertex_to in self.vertices
`self[vertex_to]`, для этих же целей ведь определяем `__getitem__`

2020-10-07 17:32 UTC, akhtyamovpavel commented on automaton_t.py
> +        with open(filename, 'r') as input_file, open(os.devnull, 'w') as output_file:
Оочень опасно читать таким образом! Может быть, использовать какой-то нормальный формат - например, JSON?

2020-10-07 17:32 UTC, akhtyamovpavel commented on automaton_t.py
> +            for word, neighbors in new_automaton[vertex].edges.items():
Нельзя ли это разбить на несколько функций? А то несколько for-ов в одной функции - это перебор

2020-10-07 17:32 UTC, akhtyamovpavel commented on automaton_t.py
> +            missing_edges += [(vertex, letter) for letter in self.alphabet if letter not in vertex.edges]
Может быть, перейти с пар на `namedtuple`?

2020-10-08 22:00 UTC, Moysenko commented on automaton_t.py
> +        with open(filename, 'r') as input_file, open(os.devnull, 'w') as output_file:
Этот метод нужен скорее для тестов, а в них хочется проверить, что именно из стандартного потока вводится корректно. Наверное, в общем случае в коде лучше заменить такой метод на считывание json'ок, но тут мне это кажется не нужным

2020-10-09 21:36 UTC, Moysenko commented
Только сейчас узнал, что надо письмо переотправить, чтобы посмотрели код.
Извиняюсь

>

2020-10-16 21:52 UTC, merged